name: todo_api
description: An new Dart Frog application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.1 <4.0.0"

dependencies:
  dart_frog: ^0.3.0
  equatable: ^2.0.5
  json_annotation: ^4.8.1
  meta: ^1.9.1
  uuid: ^3.0.7

dev_dependencies:
  build_runner: ^2.4.5
  json_serializable: ^6.7.0
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^5.0.0+1
